openapi: 3.0.0
info:
  title: Test api
  version: 1.0.0
paths:
  /api:
    get:
      responses:
        200:
          description: Hello c'est fichier openapi
          content:
            application/json:
              example: { "message": "Hello c'est fichier openapi" }
